#LDFLAGS += -static
LDFLAGS += -L../../lib/ftMPSSE/$(PLATFORM)/$(ARCH) 
LDFLAGS += -lMPSSE
#LDFLAGS += -l:../../lib/windows/i386/libMPSSE.a

# for ftd2xx
CPPFLAGS += -I../../include/ftMPSSE/$(PLATFORM)

include ../Makefile.include